platform :ios, '11.0'
inhibit_all_warnings!

target 'iosTestePortugal' do

  use_frameworks!
  pod 'Alamofire', '4.9.1'
  pod 'AlamofireImage'

  target 'iosTestePortugalTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end
